###########
# VCUtils
# General Utility for VaultCraft (July 19, 2014)
# Authors:
#  Connor Hollasch
#  Nick Peterson
###########
name: VCUtils
version: 1.0
load: STARTUP
authors: [IModZombies4Fun, Tacticalsk8er]
main: net.vaultcraft.vcutils.VCUtils